## This file is automatically generated by AutoDoc.
## Changes will be discarded by the next call of the AutoDoc method.


AUTODOC_file_scan_list := [ "../PackageInfo.g", "../examples/IntegerPartitions.g", "../examples/LoadPackage.g", "../examples/NumericalSets.g", "../examples/conversions1.g", "../examples/conversions2.g", "../gap/IntegerPartitions.gd", "../gap/IntegerPartitions.gi", "../gap/IntegerPartitions2.gd", "../gap/IntegerPartitions2.gi", "../gap/IntegerPartitions3.gd", "../gap/IntegerPartitions3.gi", "../gap/IntegerPartitionsSG.gd", "../gap/IntegerPartitionsSG.gi", "../gap/NumericalSets.gd", "../gap/NumericalSets.gi", "../gap/NumericalSets2.gd", "../gap/NumericalSets2.gi", "../gap/NumericalSets3.gd", "../gap/NumericalSets3.gi", "../gap/NumericalSetsSG.gd", "../gap/NumericalSetsSG.gi", "../gap/conversions.gd", "../gap/conversions.gi", "../gap/conversions2.gi", "../gap/nsg.gd", "../gap/nsg.gi", "../gap/random.gd", "../gap/random.gi", "../gap/tree.gd", "../gap/tree.gi", "../init.g", "../makedoc.g", "../maketest.g", "../read.g", "/home/naaci/nsip/doc/_Chunks.xml" ];

LoadPackage( "GAPDoc" );

example_tree := ExtractExamples( Directory("/home/naaci/.gap/pkg/nsip/doc/"), "nsip.xml", AUTODOC_file_scan_list, 500 );

RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );

QUIT;
