# nsip, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip04.tst");

# doc/_Chapter_Conversions.xml:13-16
gap> S := NumericalSet( [0,3,4,5,7] );
{0,3,4,5,7,->}

# doc/_Chapter_Conversions.xml:18-23
gap> P := IntegerPartition( S );
    A 11 6=3+1+1+1
gap> S  = NumericalSet( P );
true

# doc/_Chapter_Conversions.xml:62-67
gap> S := NumericalSet( P );
{0,3,4,5,7,->}
gap> P  = IntegerPartition( S );
true

# doc/_Chapter_Conversions.xml:72-75
gap> S := NumericalSet( [0,3,4,5,7] );
{0,3,4,5,7,->}

# doc/_Chapter_Conversions.xml:77-80
gap> P := IntegerPartition( S );
    A 11 6=3+1+1+1

# doc/_Chapter_Conversions.xml:82-85
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Conversions.xml:87-90
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Conversions.xml:92-95
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Conversions.xml:97-100
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Conversions.xml:102-105
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Conversions.xml:107-110
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Conversions.xml:112-115
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Conversions.xml:117-120
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Conversions.xml:122-125
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Conversions.xml:127-130
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Conversions.xml:132-135
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Conversions.xml:137-140
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Conversions.xml:142-145
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Conversions.xml:147-150
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Conversions.xml:152-155
gap> IsNSG( S ) = IsNSG( P );
true

# doc/_Chapter_Conversions.xml:157-160
gap> IsArf( S ) = IsArf( P );
true

# doc/_Chapter_Conversions.xml:162-165
gap> not IsNSG( P ) or IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Conversions.xml:167-170
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Conversions.xml:172-175
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Conversions.xml:177-180
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Conversions.xml:182-185
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Conversions.xml:187-190
gap> SpecialSubdiagram( NumericalSet( P ) ) = NumericalSet( SpecialSubdiagram( P ));
true

# doc/_Chapter_Conversions.xml:192-195
gap> IntegerPartition( SpecialSubdiagram( S ) ) = SpecialSubdiagram( IntegerPartition( S ));
true

# doc/_Chapter_Conversions.xml:197-200
gap> Reduce( IntegerPartition( S ) ) = IntegerPartition( Reduce( S ));
true

# doc/_Chapter_Conversions.xml:202-205
gap> Reduce( NumericalSet( P ) ) = NumericalSet( Reduce( P ));
true

#
gap> STOP_TEST("nsip04.tst", 1);
