# nsip, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip02.tst");

# doc/_Chapter_Numerical_Sets.xml:49-52
gap> S := NumericalSet([0,3,4,5,7]);
{0,3,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:55-58
gap> T := NumericalSetByGaps([1,2,6]);
{0,3,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:61-64
gap> S  = T;
true

# doc/_Chapter_Numerical_Sets.xml:295-298
gap> SmallElements(S);
[ 0, 3, 4, 5, 7 ]

# doc/_Chapter_Numerical_Sets.xml:301-304
gap> Genus(S);
3

# doc/_Chapter_Numerical_Sets.xml:307-310
gap> Length(S);
4

# doc/_Chapter_Numerical_Sets.xml:313-316
gap> FrobeniusNumber(S);
6

# doc/_Chapter_Numerical_Sets.xml:319-322
gap> Conductor(S);
7

# doc/_Chapter_Numerical_Sets.xml:325-328
gap> Multiplicity(S);
3

# doc/_Chapter_Numerical_Sets.xml:331-334
gap> PseudoFrobeniusNumbers(S);
[ 6 ]

# doc/_Chapter_Numerical_Sets.xml:337-340
gap> Type(S);
1

# doc/_Chapter_Numerical_Sets.xml:343-346
gap> Atom(S);
{0,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:349-352
gap> Dual(S);
{0,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:355-358
gap> GapsOfFirstType(S);
[ 1, 2, 6 ]

# doc/_Chapter_Numerical_Sets.xml:361-364
gap> GapsOfSecondType(S);
[  ]

# doc/_Chapter_Numerical_Sets.xml:367-370
gap> IsNegativeSemiSymmetric(S);
true

# doc/_Chapter_Numerical_Sets.xml:373-376
gap> IsPositiveSemiSymmetric(S);
false

# doc/_Chapter_Numerical_Sets.xml:379-382
gap> IsSemiSymmetric(S);
true

# doc/_Chapter_Numerical_Sets.xml:385-388
gap> IsSymmetric(S);
false

# doc/_Chapter_Numerical_Sets.xml:391-394
gap> IsAlmostSymmetric(S);
true

#
gap> STOP_TEST("nsip02.tst", 1);
