# nsip, chapter 8
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip06.tst");

# doc/_Chapter_Common.xml:10-12
gap> S := NumericalSet( P );;

# doc/_Chapter_Common.xml:15-18
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:21-24
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common.xml:27-30
gap> P = ConjugateOf( ConjugateOf( P ) );
true

# doc/_Chapter_Common.xml:33-36
gap> S = ConjugateOf( ConjugateOf( S ) );
true

# doc/_Chapter_Common.xml:39-42
gap> P = Dual( Dual( P ) );
true

# doc/_Chapter_Common.xml:45-48
gap> S = Dual( Dual( S ) );
true

# doc/_Chapter_Common.xml:51-54
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common.xml:57-60
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Common.xml:63-66
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common.xml:69-72
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common.xml:75-78
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common.xml:81-84
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common.xml:87-90
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common.xml:93-96
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common.xml:99-102
gap> IsPseudoSymmetric( S ) = IsPseudoSymmetric( P );
true

# doc/_Chapter_Common.xml:105-108
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common.xml:111-114
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common.xml:117-120
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common.xml:123-126
gap> IsPerfectSemigroup( S ) = IsPerfectSemigroup( P );
true

# doc/_Chapter_Common.xml:129-132
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common.xml:135-138
gap> N( S ) = N( P );
true

# doc/_Chapter_Common.xml:141-144
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:147-150
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common.xml:153-156
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:159-162
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Common.xml:165-168
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:171-174
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common.xml:177-180
gap> P = ConjugateOf( ConjugateOf( P ) );
true

# doc/_Chapter_Common.xml:183-186
gap> S = ConjugateOf( ConjugateOf( S ) );
true

# doc/_Chapter_Common.xml:189-192
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common.xml:195-198
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Common.xml:201-204
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common.xml:207-210
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common.xml:213-216
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common.xml:219-222
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common.xml:225-228
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common.xml:231-234
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common.xml:237-240
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common.xml:243-246
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common.xml:249-252
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common.xml:255-258
gap> IsPerfectSemigroup( S ) = IsPerfectSemigroup( P );
true

# doc/_Chapter_Common.xml:261-264
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common.xml:267-270
gap> N( S ) = N( P );
true

# doc/_Chapter_Common.xml:273-276
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:279-282
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common.xml:285-288
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:291-294
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Common.xml:297-300
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:303-306
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common.xml:309-312
gap> IsNSG( P );
true

# doc/_Chapter_Common.xml:315-318
gap> P = ConjugateOf( ConjugateOf( P ) );
true

# doc/_Chapter_Common.xml:321-324
gap> S = ConjugateOf( ConjugateOf( S ) );
true

# doc/_Chapter_Common.xml:327-330
gap> P = Dual( Dual( P ) );
true

# doc/_Chapter_Common.xml:333-336
gap> S = Dual( Dual( S ) );
true

# doc/_Chapter_Common.xml:339-342
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common.xml:345-348
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Common.xml:351-354
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common.xml:357-360
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common.xml:363-366
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common.xml:369-372
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common.xml:375-378
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common.xml:381-384
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common.xml:387-390
gap> IsPseudoSymmetric( S ) = IsPseudoSymmetric( P );
true

# doc/_Chapter_Common.xml:393-396
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common.xml:399-402
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common.xml:405-408
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common.xml:411-414
gap> IsPerfectSemigroup( S ) = IsPerfectSemigroup( P );
true

# doc/_Chapter_Common.xml:417-420
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common.xml:423-426
gap> N( S ) = N( P );
true

# doc/_Chapter_Common.xml:429-432
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:435-438
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common.xml:441-444
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common.xml:447-450
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

#
gap> STOP_TEST("nsip06.tst", 1);
