# nsip, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip03.tst");

# doc/_Chapter_Integer_Partitions.xml:21-24
gap> P := IntegerPartition([7,2,1,1]);
SG  A + 11= 7+ 2+ 1+ 1

#
gap> STOP_TEST("nsip03.tst", 1);
