# nsip, chapter 3
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip03.tst");

# doc/_Chapter_Integer_Partitions.xml:25-28
gap> P := IntegerPartition([7,3,1,1]);
    A 52 12=7+3+1+1

# doc/_Chapter_Integer_Partitions.xml:30-33
gap> Gaps(P);
[ 1, 2, 3, 4, 6, 7, 10 ]

# doc/_Chapter_Integer_Partitions.xml:35-38
gap> GapsOfFirstType(P);
[ 1, 2, 10 ]

# doc/_Chapter_Integer_Partitions.xml:40-43
gap> GapsOfSecondType(P);
[ 3, 4, 6, 7 ]

# doc/_Chapter_Integer_Partitions.xml:45-48
gap> Genus(P);
7

# doc/_Chapter_Integer_Partitions.xml:50-53
gap> Length(P);
4

# doc/_Chapter_Integer_Partitions.xml:55-58
gap> FrobeniusNumber(P);
10

# doc/_Chapter_Integer_Partitions.xml:60-63
gap> IsSymmetric(P);
false

# doc/_Chapter_Integer_Partitions.xml:65-68
gap> IsPositiveSemiSymmetric(P);
false

# doc/_Chapter_Integer_Partitions.xml:70-73
gap> IsNegativeSemiSymmetric(P);
false

# doc/_Chapter_Integer_Partitions.xml:75-78
gap> IsAlmostSymmetric(P);
true

# doc/_Chapter_Integer_Partitions.xml:80-83
gap> Type(P);
5

# doc/_Chapter_Integer_Partitions.xml:85-88
gap> ConjugateOf(P);
    A 22 12=4+2+2+1+1+1+1

# doc/_Chapter_Integer_Partitions.xml:90-93
gap> Dual(P);
    - 24 23=7+6+6+4

# doc/_Chapter_Integer_Partitions.xml:95-98
gap> Total(P);
12

# doc/_Chapter_Integer_Partitions.xml:100-103
gap> Trace(P);
2

# doc/_Chapter_Integer_Partitions.xml:105-108
gap> IsNSG(P);
false

# doc/_Chapter_Integer_Partitions.xml:110-113
gap> IsArf(P);
false

# doc/_Chapter_Integer_Partitions.xml:115-118
gap> IsOdd(P);
true

# doc/_Chapter_Integer_Partitions.xml:120-123
gap> IsStrict(P);
false

# doc/_Chapter_Integer_Partitions.xml:125-128
gap> EulerBijection(EulerBijection(P))=P;
true

# doc/_Chapter_Integer_Partitions.xml:130-133
gap> P := IntegerPartition([7,2,1,1]);
SG  A 42 11=7+2+1+1

# doc/_Chapter_Integer_Partitions.xml:135-138
gap> P := IntegerPartition([7,2,1,1]);
SG  A 42 11=7+2+1+1

# doc/_Chapter_Integer_Partitions.xml:140-143
gap> Gaps(P);
[ 1, 2, 3, 4, 5, 7, 10 ]

# doc/_Chapter_Integer_Partitions.xml:145-148
gap> GapsOfFirstType(P);
[ 1, 2, 4, 10 ]

# doc/_Chapter_Integer_Partitions.xml:150-153
gap> GapsOfSecondType(P);
[ 3, 5, 7 ]

# doc/_Chapter_Integer_Partitions.xml:155-158
gap> Genus(P);
7

# doc/_Chapter_Integer_Partitions.xml:160-163
gap> Length(P);
4

# doc/_Chapter_Integer_Partitions.xml:165-168
gap> FrobeniusNumber(P);
10

# doc/_Chapter_Integer_Partitions.xml:170-173
gap> IsSymmetric(P);
false

# doc/_Chapter_Integer_Partitions.xml:175-178
gap> IsPseudoSymmetric(P);
false

# doc/_Chapter_Integer_Partitions.xml:180-183
gap> IsPositiveSemiSymmetric(P);
false

# doc/_Chapter_Integer_Partitions.xml:185-188
gap> IsNegativeSemiSymmetric(P);
true

# doc/_Chapter_Integer_Partitions.xml:190-193
gap> IsAlmostSymmetric(P);
true

# doc/_Chapter_Integer_Partitions.xml:195-198
gap> Type(P);
4

# doc/_Chapter_Integer_Partitions.xml:200-203
gap> ConjugateOf(P);
    A 12 11=4+2+1+1+1+1+1

# doc/_Chapter_Integer_Partitions.xml:205-208
gap> Dual(P);
      24 24=7+6+6+5

# doc/_Chapter_Integer_Partitions.xml:210-213
gap> Total(P);
11

# doc/_Chapter_Integer_Partitions.xml:215-218
gap> Trace(P);
2

# doc/_Chapter_Integer_Partitions.xml:220-223
gap> IsNSG(P);
true

# doc/_Chapter_Integer_Partitions.xml:225-228
gap> IsArf(P);
false

# doc/_Chapter_Integer_Partitions.xml:279-281
gap> P := IntegerPartition([19,19,17,17,17,13,1,1,1,1]);;

# doc/_Chapter_Integer_Partitions.xml:283-286
gap> IsOdd(P);
true

# doc/_Chapter_Integer_Partitions.xml:288-290
gap> S := EulerBijection(P);;

# doc/_Chapter_Integer_Partitions.xml:292-295
gap> IsStrict(S);
true

# doc/_Chapter_Integer_Partitions.xml:297-300
gap> EulerBijection(S) = P;
true

# doc/_Chapter_Integer_Partitions.xml:307-309
gap> P := IntegerPartition([19,17,13,1]);;

# doc/_Chapter_Integer_Partitions.xml:311-313
gap> S := Bend(P);;

# doc/_Chapter_Integer_Partitions.xml:315-318
gap> IsOdd(P);
true

# doc/_Chapter_Integer_Partitions.xml:320-323
gap> IsStrict(P);
true

# doc/_Chapter_Integer_Partitions.xml:325-328
gap> IsSymmetric(S);
true

# doc/_Chapter_Integer_Partitions.xml:330-333
gap> UnBend(S) = P;
true

# doc/_Chapter_Integer_Partitions.xml:335-338
gap> EulerBijection(P) = P;
true

#
gap> STOP_TEST("nsip03.tst", 1);
