# nsip, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip02.tst");

# doc/_Chapter_Numerical_Sets.xml:49-52
gap> S := NumericalSet([0,3,4,5,7]);
{0,3,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:55-58
gap> T := NumericalSetByGaps([1,2,6]);
{0,3,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:61-64
gap> S  = T;
true

# doc/_Chapter_Numerical_Sets.xml:305-308
gap> SmallElements(S);
[ 0, 3, 4, 5, 7 ]

# doc/_Chapter_Numerical_Sets.xml:311-314
gap> Genus(S);
3

# doc/_Chapter_Numerical_Sets.xml:317-320
gap> Length(S);
4

# doc/_Chapter_Numerical_Sets.xml:323-326
gap> FrobeniusNumber(S);
6

# doc/_Chapter_Numerical_Sets.xml:329-332
gap> Conductor(S);
7

# doc/_Chapter_Numerical_Sets.xml:335-338
gap> Multiplicity(S);
3

# doc/_Chapter_Numerical_Sets.xml:341-344
gap> PseudoFrobeniusNumbers(S);
[ 6 ]

# doc/_Chapter_Numerical_Sets.xml:347-350
gap> Type(S);
1

# doc/_Chapter_Numerical_Sets.xml:353-356
gap> Atom(S);
{0,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:359-362
gap> Dual(S);
{0,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:365-368
gap> GapsOfFirstType(S);
[ 1, 2, 6 ]

# doc/_Chapter_Numerical_Sets.xml:371-374
gap> GapsOfSecondType(S);
[  ]

# doc/_Chapter_Numerical_Sets.xml:377-380
gap> IsNegativeSemiSymmetric(S);
false

# doc/_Chapter_Numerical_Sets.xml:383-386
gap> IsPositiveSemiSymmetric(S);
true

# doc/_Chapter_Numerical_Sets.xml:389-392
gap> IsSemiSymmetric(S);
true

# doc/_Chapter_Numerical_Sets.xml:395-398
gap> IsSymmetric(S);
false

# doc/_Chapter_Numerical_Sets.xml:401-404
gap> IsAlmostSymmetric(S);
true

#
gap> STOP_TEST("nsip02.tst", 1);
