# nsip, chapter 4
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip04.tst");

# doc/_Chapter_Conversions.xml:23-28
gap> P := IntegerPartition( S );
    A  1 1 6= 3+ 1+ 1+ 1
gap> S  = NumericalSet( P );
true

# doc/_Chapter_Conversions.xml:53-58
gap> S := NumericalSet( P );
{0,3,4,5,7,->}
gap> P  = IntegerPartition( S );
true

#
gap> STOP_TEST("nsip04.tst", 1);
