# nsip, chapter 8
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip05.tst");

# doc/_Chapter_Common_Methods.xml:130-133
gap> PseudoFrobeniusNumbers(S);
[ 6 ]

# doc/_Chapter_Common_Methods.xml:135-138
gap> Type(S);
1

# doc/_Chapter_Common_Methods.xml:140-143
gap> Atom(S);
{0,4,5,7,->}

# doc/_Chapter_Common_Methods.xml:145-148
gap> ConjugateOf(S);
{0,4,5,7,->}

# doc/_Chapter_Common_Methods.xml:150-153
gap> GapsOfFirstType(S);
[ 1, 2, 6 ]

# doc/_Chapter_Common_Methods.xml:155-158
gap> GapsOfSecondType(S);
[  ]

# doc/_Chapter_Common_Methods.xml:160-163
gap> IsNegativeSemiSymmetric(S);
false

# doc/_Chapter_Common_Methods.xml:165-168
gap> IsPositiveSemiSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:170-173
gap> IsSemiSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:175-178
gap> IsSymmetric(S);
false

# doc/_Chapter_Common_Methods.xml:180-183
gap> IsAlmostSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:185-188
gap> NonzeroSmallElements( S );
[ 3, 4, 5 ]

# doc/_Chapter_Common_Methods.xml:218-221
gap> Conductor( S );
7

# doc/_Chapter_Common_Methods.xml:223-226
gap> Multiplicity( S );
3

# doc/_Chapter_Common_Methods.xml:228-231
gap> Length( S );
4

# doc/_Chapter_Common_Methods.xml:233-236
gap> Gaps( S );
[ 1, 2, 6 ]

# doc/_Chapter_Common_Methods.xml:238-241
gap> FrobeniusNumber( S );
6

# doc/_Chapter_Common_Methods.xml:243-246
gap> Genus( S );
3

# doc/_Chapter_Common_Methods.xml:248-251
gap> CClosure( S );
{0,3,->}

# doc/_Chapter_Common_Methods.xml:253-256
gap> Total( S );
6

# doc/_Chapter_Common_Methods.xml:258-261
gap> Trace( S );
1

# doc/_Chapter_Common_Methods.xml:263-266
gap> Weight( S );
6

# doc/_Chapter_Common_Methods.xml:276-279
gap> P := IntegerPartition( [7,2,1,1] );
SG  A 42 11=7+2+1+1

# doc/_Chapter_Common_Methods.xml:281-284
gap> S := NumericalSet( P );
{0,6,8,9,11,->}

# doc/_Chapter_Common_Methods.xml:286-289
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:291-294
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common_Methods.xml:296-299
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common_Methods.xml:301-304
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common_Methods.xml:306-309
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common_Methods.xml:311-314
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common_Methods.xml:316-319
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common_Methods.xml:321-324
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common_Methods.xml:326-329
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:331-334
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:336-339
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:341-344
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:346-349
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common_Methods.xml:351-354
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:356-359
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common_Methods.xml:361-364
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:366-369
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Common_Methods.xml:378-380
gap> S := NumericalSet( P );;

# doc/_Chapter_Common_Methods.xml:382-385
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:387-390
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common_Methods.xml:392-395
gap> P = ConjugateOf( ConjugateOf( P ) );
true

# doc/_Chapter_Common_Methods.xml:397-400
gap> S = ConjugateOf( ConjugateOf( S ) );
true

# doc/_Chapter_Common_Methods.xml:402-405
gap> P = Dual( Dual( P ) );
true

# doc/_Chapter_Common_Methods.xml:407-410
gap> S = Dual( Dual( S ) );
true

# doc/_Chapter_Common_Methods.xml:412-415
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common_Methods.xml:417-420
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Common_Methods.xml:422-425
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common_Methods.xml:427-430
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common_Methods.xml:432-435
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common_Methods.xml:437-440
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common_Methods.xml:442-445
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common_Methods.xml:447-450
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:452-455
gap> IsPseudoSymmetric( S ) = IsPseudoSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:457-460
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:462-465
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:467-470
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:472-475
gap> IsPerfectSemigroup( S ) = IsPerfectSemigroup( P );
true

# doc/_Chapter_Common_Methods.xml:477-480
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common_Methods.xml:482-485
gap> N( S ) = N( P );
true

# doc/_Chapter_Common_Methods.xml:487-490
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:492-495
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common_Methods.xml:497-500
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:502-505
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Common_Methods.xml:507-510
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:512-515
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common_Methods.xml:517-520
gap> P = ConjugateOf( ConjugateOf( P ) );
true

# doc/_Chapter_Common_Methods.xml:522-525
gap> S = ConjugateOf( ConjugateOf( S ) );
true

# doc/_Chapter_Common_Methods.xml:527-530
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common_Methods.xml:532-535
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Common_Methods.xml:537-540
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common_Methods.xml:542-545
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common_Methods.xml:547-550
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common_Methods.xml:552-555
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common_Methods.xml:557-560
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common_Methods.xml:562-565
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:567-570
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:572-575
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:577-580
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:582-585
gap> IsPerfectSemigroup( S ) = IsPerfectSemigroup( P );
true

# doc/_Chapter_Common_Methods.xml:587-590
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common_Methods.xml:592-595
gap> N( S ) = N( P );
true

# doc/_Chapter_Common_Methods.xml:597-600
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:602-605
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common_Methods.xml:607-610
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:612-615
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Common_Methods.xml:617-620
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:622-625
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common_Methods.xml:627-630
gap> IsNSG( P );
true

# doc/_Chapter_Common_Methods.xml:632-635
gap> P = ConjugateOf( ConjugateOf( P ) );
true

# doc/_Chapter_Common_Methods.xml:637-640
gap> S = ConjugateOf( ConjugateOf( S ) );
true

# doc/_Chapter_Common_Methods.xml:642-645
gap> P = Dual( Dual( P ) );
true

# doc/_Chapter_Common_Methods.xml:647-650
gap> S = Dual( Dual( S ) );
true

# doc/_Chapter_Common_Methods.xml:652-655
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common_Methods.xml:657-660
gap> Parts( S ) = Parts( P );
true

# doc/_Chapter_Common_Methods.xml:662-665
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common_Methods.xml:667-670
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common_Methods.xml:672-675
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common_Methods.xml:677-680
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common_Methods.xml:682-685
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common_Methods.xml:687-690
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:692-695
gap> IsPseudoSymmetric( S ) = IsPseudoSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:697-700
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:702-705
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:707-710
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:712-715
gap> IsPerfectSemigroup( S ) = IsPerfectSemigroup( P );
true

# doc/_Chapter_Common_Methods.xml:717-720
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common_Methods.xml:722-725
gap> N( S ) = N( P );
true

# doc/_Chapter_Common_Methods.xml:727-730
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:732-735
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common_Methods.xml:737-740
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:742-745
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

#
gap> STOP_TEST("nsip05.tst", 1);
