# nsip, chapter 9
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip06.tst");

# doc/_Chapter_Numerical_Sets_2.xml:13-16
gap> S := NumericalSet([3,8]);
{0,3,8,->}

# doc/_Chapter_Numerical_Sets_2.xml:18-21
gap> SmallElementsAlt( S );
[ 0, 3, 8 ]

# doc/_Chapter_Numerical_Sets_2.xml:23-26
gap> Gaps( S );
[ 1, 2, 4, 5, 6, 7 ]

# doc/_Chapter_Numerical_Sets_2.xml:28-31
gap> GapsOfFirstType( S );
[ 4, 7 ]

# doc/_Chapter_Numerical_Sets_2.xml:33-36
gap> GapsOfSecondType( S );
[ 1, 2, 5, 6 ]

# doc/_Chapter_Numerical_Sets_2.xml:38-41
gap> Genus( S );
6

# doc/_Chapter_Numerical_Sets_2.xml:43-46
gap> Length( S );
2

# doc/_Chapter_Numerical_Sets_2.xml:48-51
gap> FrobeniusNumber( S );
7

# doc/_Chapter_Numerical_Sets_2.xml:53-56
gap> IsSymmetric( S );
false

# doc/_Chapter_Numerical_Sets_2.xml:58-61
gap> IsPositiveSemiSymmetric( S );
false

# doc/_Chapter_Numerical_Sets_2.xml:63-66
gap> IsNegativeSemiSymmetric( S );
true

# doc/_Chapter_Numerical_Sets_2.xml:68-71
gap> IsAlmostSymmetric( S );
false

# doc/_Chapter_Numerical_Sets_2.xml:73-76
gap> Type( S );
3

# doc/_Chapter_Numerical_Sets_2.xml:78-81
gap> ConjugateOf( S );
{0,1,2,3,5,6,8,->}

# doc/_Chapter_Numerical_Sets_2.xml:83-86
gap> Dual( S );
{0,5,8,->}

# doc/_Chapter_Numerical_Sets_2.xml:88-91
gap> IsSemiSymmetric( S );
false

# doc/_Chapter_Numerical_Sets_2.xml:93-96
gap> PseudoFrobeniusNumbers( S );
[ 5, 6, 7 ]

# doc/_Chapter_Numerical_Sets_2.xml:98-101
gap> Atom( S );
{0,8,->}

# doc/_Chapter_Numerical_Sets_2.xml:103-106
gap> SmallElementsAlt( S );
[ 0, 3, 8 ]

# doc/_Chapter_Numerical_Sets_2.xml:108-111
gap> Conductor( S );
8

# doc/_Chapter_Numerical_Sets_2.xml:113-116
gap> Multiplicity( S );
3

# doc/_Chapter_Numerical_Sets_2.xml:118-121
gap> CClosure( S );
{0,3,6,8,->}

#
gap> STOP_TEST("nsip06.tst", 1);
