# nsip, chapter 2
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip02.tst");

# doc/_Chapter_Numerical_Sets.xml:49-52
gap> S := NumericalSet([0,3,4,5,7]);
{0,3,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:55-58
gap> S := NumericalSetByGaps([1,2,6]);
{0,3,4,5,7,->}

# doc/_Chapter_Numerical_Sets.xml:312-315
gap> SmallElements(S);
[ 0, 3, 4, 5, 7 ]

# doc/_Chapter_Numerical_Sets.xml:318-321
gap> Genus(S);
3

# doc/_Chapter_Numerical_Sets.xml:324-327
gap> Length(S);
4

# doc/_Chapter_Numerical_Sets.xml:330-333
gap> FrobeniusNumber(S);
6

# doc/_Chapter_Numerical_Sets.xml:336-339
gap> Conductor(S);
7

# doc/_Chapter_Numerical_Sets.xml:342-345
gap> Multiplicity(S);
3

#
gap> STOP_TEST("nsip02.tst", 1);
