# nsip, chapter 5
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip05.tst");

# doc/_Chapter_Common_Methods.xml:129-132
gap> PseudoFrobeniusNumbers(S);
[ 6 ]

# doc/_Chapter_Common_Methods.xml:135-138
gap> Type(S);
1

# doc/_Chapter_Common_Methods.xml:141-144
gap> Atom(S);
{0,4,5,7,->}

# doc/_Chapter_Common_Methods.xml:147-150
gap> ConjugateOf(S);
{0,4,5,7,->}

# doc/_Chapter_Common_Methods.xml:153-156
gap> GapsOfFirstType(S);
[ 1, 2, 6 ]

# doc/_Chapter_Common_Methods.xml:159-162
gap> GapsOfSecondType(S);
[  ]

# doc/_Chapter_Common_Methods.xml:165-168
gap> IsNegativeSemiSymmetric(S);
false

# doc/_Chapter_Common_Methods.xml:171-174
gap> IsPositiveSemiSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:177-180
gap> IsSemiSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:183-186
gap> IsSymmetric(S);
false

# doc/_Chapter_Common_Methods.xml:189-192
gap> IsAlmostSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:207-210
gap> P := IntegerPartition( [7,2,1,1] );
SG  A 42 11=7+2+1+1

# doc/_Chapter_Common_Methods.xml:213-216
gap> S := NumericalSet( P );
{0,6,8,9,11,->}

# doc/_Chapter_Common_Methods.xml:219-222
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:225-228
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common_Methods.xml:231-234
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common_Methods.xml:237-240
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common_Methods.xml:243-246
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common_Methods.xml:249-252
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common_Methods.xml:255-258
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common_Methods.xml:261-264
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common_Methods.xml:267-270
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:273-276
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:279-282
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:285-288
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:291-294
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common_Methods.xml:297-300
gap> IntegerPartition( ConjugateOf( S )) = ConjugateOf( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:303-306
gap> ConjugateOf( NumericalSet( P ) ) = NumericalSet( ConjugateOf( P ));
true

# doc/_Chapter_Common_Methods.xml:309-312
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:315-318
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

#
gap> STOP_TEST("nsip05.tst", 1);
