# nsip, chapter 5
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been generated by AutoDoc. It contains examples extracted from
# the package documentation. Each example is preceded by a comment which gives
# the name of a GAPDoc XML file and a line range from which the example were
# taken. Note that the XML file in turn may have been generated by AutoDoc
# from some other input.
#
gap> START_TEST("nsip05.tst");

# doc/_Chapter_Common_Methods.xml:129-132
gap> PseudoFrobeniusNumbers(S);
[ 6 ]

# doc/_Chapter_Common_Methods.xml:135-138
gap> Type(S);
1

# doc/_Chapter_Common_Methods.xml:141-144
gap> Atom(S);
{0,4,5,7,->}

# doc/_Chapter_Common_Methods.xml:147-150
gap> Dual(S);
{0,4,5,7,->}

# doc/_Chapter_Common_Methods.xml:153-156
gap> GapsOfFirstType(S);
[ 1, 2, 6 ]

# doc/_Chapter_Common_Methods.xml:159-162
gap> GapsOfSecondType(S);
[  ]

# doc/_Chapter_Common_Methods.xml:165-168
gap> IsNegativeSemiSymmetric(S);
false

# doc/_Chapter_Common_Methods.xml:171-174
gap> IsPositiveSemiSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:177-180
gap> IsSemiSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:183-186
gap> IsSymmetric(S);
false

# doc/_Chapter_Common_Methods.xml:189-192
gap> IsAlmostSymmetric(S);
true

# doc/_Chapter_Common_Methods.xml:235-238
gap> P := IntegerPartition( [7,2,1,1] );
SG  A - 4 2 11= 7+ 2+ 1+ 1

# doc/_Chapter_Common_Methods.xml:241-244
gap> S := NumericalSet( P );
{0,6,8,9,11,->}

# doc/_Chapter_Common_Methods.xml:247-250
gap> S  = NumericalSet( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:253-256
gap> P  = IntegerPartition( NumericalSet( P ) );
true

# doc/_Chapter_Common_Methods.xml:259-262
gap> Gaps( S ) = Gaps( P );
true

# doc/_Chapter_Common_Methods.xml:265-268
gap> GapsOfFirstType( S ) = GapsOfFirstType( P );
true

# doc/_Chapter_Common_Methods.xml:271-274
gap> GapsOfSecondType( S ) = GapsOfSecondType( P );
true

# doc/_Chapter_Common_Methods.xml:277-280
gap> Genus( S ) = Genus( P );
true

# doc/_Chapter_Common_Methods.xml:283-286
gap> Length( S ) = Length( P );
true

# doc/_Chapter_Common_Methods.xml:289-292
gap> FrobeniusNumber( S ) = FrobeniusNumber( P );
true

# doc/_Chapter_Common_Methods.xml:295-298
gap> IsSymmetric( S ) = IsSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:301-304
gap> IsPositiveSemiSymmetric( S ) = IsPositiveSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:307-310
gap> IsNegativeSemiSymmetric( S ) = IsNegativeSemiSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:313-316
gap> IsAlmostSymmetric( S ) = IsAlmostSymmetric( P );
true

# doc/_Chapter_Common_Methods.xml:319-322
gap> Type( S ) = Type( P );
true

# doc/_Chapter_Common_Methods.xml:325-328
gap> IntegerPartition( Dual( S )) = Dual( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:331-334
gap> Dual( NumericalSet( P ) ) = NumericalSet( Dual( P ));
true

# doc/_Chapter_Common_Methods.xml:337-340
gap> IntegerPartition( Dual2( S )) = Dual2( IntegerPartition( S ) );
true

# doc/_Chapter_Common_Methods.xml:343-346
gap> Dual2( NumericalSet( P ) ) = NumericalSet( Dual2( P ));
true

#
gap> STOP_TEST("nsip05.tst", 1);
