name: Build manuals

# Trigger the workflow on push to master / main, or on pull request
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  manual:
    name: Build manuals
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: gap-actions/setup-gap@v3
      - uses: gap-actions/build-pkg-docs@v2
        with:
          use-latex: 'true'
          warnings-as-errors: 'false'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v7
        with:
          archive: 'false'
          path: ./doc/manual.pdf
