name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # The CI test job
  test:
    name: CI test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        gap-version:
          - 'devel'
          - '4.16'
          - '4.15'
          - '4.14'
          - '4.13'
          - '4.12'

    steps:
      - uses: actions/checkout@v7
      - uses: gap-actions/setup-gap@v3
        with:
          gap-version: ${{ matrix.gap-version }}
      - uses: gap-actions/build-pkg@v3
      - uses: gap-actions/run-pkg-tests@v4
